<a href="https://colab.research.google.com/github/KurumiZaphkielll/MikuNakano.github.io/blob/main/udmy8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eliminación de columnas de un DataFrame con Pandas

En este programa se carga un archivo de Excel con información de la NBA y se muestra cómo eliminar una o varias columnas del DataFrame utilizando `drop()`.

## 1. Importación, carga y visualización de los datos

Se importa la librería **Pandas** y se utiliza `pd.read_excel()` para cargar el archivo `Nba Teams.xlsx` en el DataFrame `nba`.

Finalmente, `nba.head()` permite visualizar las primeras cinco filas para comprobar que los datos fueron cargados correctamente.

In [ ]:
import pandas as pd
nba = pd.read_excel("Nba Teams.xlsx")
nba.head()

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH

## 2. Eliminación temporal de una columna

La instrucción `nba.drop("Salary", axis=1)` elimina temporalmente la columna `Salary` del DataFrame y muestra el resultado sin modificar el DataFrame original, ya que no se utiliza `inplace=True`.

In [ ]:
nba.drop("Salary", axis = 1)

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,CH
...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,US

## 3. Visualización del DataFrame original

La instrucción `nba` permite visualizar nuevamente el DataFrame original. Como la eliminación anterior no utilizó `inplace=True`, la columna `Salary` permanece en el DataFrame.

In [ ]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Salary,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,18000000.0,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,1701593.0,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,1517981.0,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,NaN,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,16000000.0,CH
...,...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,4692840.0,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,41358814.0,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,8333333.0,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,3372840.0,US

## 4. Eliminación permanente de una columna

La instrucción `nba.drop("Salary", axis=1, inplace=True)` elimina la columna `Salary` del DataFrame `nba` de forma permanente.

El parámetro `axis=1` indica que se está eliminando una columna, mientras que `inplace=True` aplica directamente el cambio sobre el DataFrame original.

In [ ]:
nba.drop("Salary", axis = 1, inplace = True)

## 5. Visualización del DataFrame actualizado

La instrucción `nba` permite visualizar nuevamente el DataFrame después de eliminar permanentemente la columna `Salary`, comprobando los cambios realizados en su estructura.

In [ ]:
nba

,Name,Team,Division,Position,Height,Weight,Birth_Date,College,Country
0,Bogdan Bogdanovic,Atlanta Hawks,SouthEast,G,6'6,220.0,1992-08-18,NaN,RS
1,Brandon Goodwin,Atlanta Hawks,SouthEast,G,NaN,180.0,1995-10-02,Central Florida,US
2,Bruno Fernando,Atlanta Hawks,SouthEast,F,6'9,240.0,1998-08-15,Maryland,AO
3,Cam Reddish,Atlanta Hawks,SouthEast,F,6'8,218.0,1999-09-01,Duke,US
4,Clint Capela,Atlanta Hawks,SouthEast,C,6'10,240.0,1994-05-18,NaN,CH
...,...,...,...,...,...,...,...,...,...
493,Rui Hachimura,Washington Wizards,SouthEast,F,6'8,230.0,1998-02-08,Gonzaga,JP
494,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN
495,Russell Westbrook,Washington Wizards,SouthEast,G,6'3,200.0,1988-11-12,UCLA,US
496,Thomas Bryant,Washington Wizards,SouthEast,C,6'10,248.0,1997-07-31,Indiana,US
497,Troy Brown Jr.,Washington Wizards,SouthEast,G-F,6'6,215.0,1999-07-28,Oregon,US

## 6. Eliminación de varias columnas

La instrucción `nba.drop(["Team", "Division"], axis=1, inplace=True)` elimina las columnas `Team` y `Division` del DataFrame `nba` de forma permanente.

El uso de una lista permite eliminar varias columnas al mismo tiempo. El parámetro `axis=1` indica que se están eliminando columnas y `inplace=True` aplica los cambios directamente sobre el DataFrame original.

In [ ]:
nba.drop(["Team", "Division"], axis = 1, inplace = True)

## 7. Visualización del DataFrame final

La instrucción `nba` permite visualizar el DataFrame después de eliminar las columnas `Team` y `Division`, mostrando la estructura final de los datos.

In [ ]:
nba

,Name,Position,Height,Weight,Birth_Date,College,Country
0,Bogdan Bogdanovic,G,6'6,220.0,1992-08-18,NaN,RS
1,Brandon Goodwin,G,NaN,180.0,1995-10-02,Central Florida,US
2,Bruno Fernando,F,6'9,240.0,1998-08-15,Maryland,AO
3,Cam Reddish,F,6'8,218.0,1999-09-01,Duke,US
4,Clint Capela,C,6'10,240.0,1994-05-18,NaN,CH
...,...,...,...,...,...,...,...
493,Rui Hachimura,F,6'8,230.0,1998-02-08,Gonzaga,JP
494,NaN,NaN,NaN,NaN,NaT,NaN,NaN
495,Russell Westbrook,G,6'3,200.0,1988-11-12,UCLA,US
496,Thomas Bryant,C,6'10,248.0,1997-07-31,Indiana,US
497,Troy Brown Jr.,G-F,6'6,215.0,1999-07-28,Oregon,US